# Generated by Django 6.0.3 on 2026-07-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='menu_order',
            field=models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше позиция', verbose_name='Порядок в меню'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_in_menu',
            field=models.BooleanField(default=False, help_text='Отметьте, чтобы категория автоматически появилась в меню', verbose_name='Показывать в меню'),
        ),
    ]
